name: Create CRD Update PR in Longhorn Repo

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
  CUSTOM_TOKEN: ${{ secrets.CUSTOM_GITHUB_ACTION_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Packages
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

